#pragma once

static struct CHUNKDATA {

	// BASIC CONSTANTS
	const static uint32_t VERTICESPERBLOCK = 8;
	const static uint32_t INDICESPERBLOCK = 36;
	const static uint32_t CHUNKSIZE = 8;
	const static uint32_t TERRAINSIZE = 8;

	// PER CHUNK CONSTANTS
	const static uint32_t BLOCKPERCHUNK = CHUNKSIZE * CHUNKSIZE * CHUNKSIZE;
	const static uint32_t VERTICESPERCHUNK = VERTICESPERBLOCK * BLOCKPERCHUNK;
	const static uint32_t INDICESPERCHUNK = INDICESPERBLOCK * BLOCKPERCHUNK;

	// GLOBAL MAXIMUMS
	const static uint32_t MAXCHUNKCOUNT = TERRAINSIZE * TERRAINSIZE;
	const static uint32_t MAXBLOCKCOUNT = BLOCKPERCHUNK * MAXCHUNKCOUNT;
	const static uint32_t MAXVERTEXCOUNT = VERTICESPERBLOCK * MAXBLOCKCOUNT;
	const static uint32_t MAXINDEXCOUNT = INDICESPERBLOCK * MAXBLOCKCOUNT;

};


